### ISSUE TITLE
Plugin update notifications not appearing for Aloha Powerpack

### ISSUE THREAD

**Issue by ryanlabelle** [PixelMakers/bellevue-issues#1]
We are aware that Aloha PowerPack plugin update notifications are not appearing and are actively working on a fix. In the meantime, you can update manually using the link below:

🔗 [Update Aloha PowerPack](https://link.bellevuetheme.com/aloha-powerpack)

You can check the latest version number here:

🔗 [Aloha PowerPack Changelog](https://bellevuetheme.com/changelog/)

Thank you for your patience!

**Comment by ryanlabelle** [comment]
Fixed.

**Comment by big-fudge** [comment]
This issue is back again:
<img width="406" height="115" alt="Image" src="https://github.com/user-attachments/assets/bd4fee9e-5dfd-49f9-9a86-30973d122f6d" />

The hint on the support site of yours also doesn't work since there is no plugin menu in the customizer.
How to install bundled plugins for free:
Go under Appearance / Customize / Theme Options / Plugins / and enable the plugin you wish to download and activate.
Publish and follow the instructions on the dashboard.
If you run into any issues, please let us know. Happy to help.

Said menu in the customizer:
<img width="302" height="468" alt="Image" src="https://github.com/user-attachments/assets/87354434-edb5-4afe-a249-94fd94df67b2" />

**Comment by moudh** [comment]
hello
can you provide me with valid link for the Aloha Powerpack update please ?
